namespace Movies.Web.ApiModels;

// ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
public class PaketDTO : CreatePaketDTO
{
  public PaketDTO(int id, string naziv, string opis, List<FilmDTO>? filmovi = null) 
    : base(naziv, opis)
  {
    Id = id;
    Filmovi = filmovi ?? new List<FilmDTO>();
  }
  public int Id { get; set; }
  public List<FilmDTO> Filmovi { get; set; }
}

// Creation DTOs should not include an ID if the ID will be generated by the back end
public abstract class CreatePaketDTO
{
  protected CreatePaketDTO(string naziv, string opis)
  {
    Naziv = naziv;
    Opis = opis;
  }
  public string Naziv { get; set; }
  public string Opis { get; set; }
  public DateTime? DatumFormiranja { get; set; }
}
